---
language: php
php:
  - '5.6'
  - '7.0'
  - 'nightly'

install:
  - composer install

before_install:
  - pecl channel-update pecl.php.net
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install yaml < /dev/null &)

script:
  - ./vendor/bin/phpcs --standard=PSR2 src/
  - ./vendor/bin/phpunit --coverage-text -c test/phpunit.xml

addons:
  apt:
    packages:
      - libyaml-dev
