---
language: php
php:
  - '5.6'
  - '7.0'
  - 'nightly'

install:
  - composer install

before_script:
  - printf "\n" | pecl install yaml-beta
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - ./vendor/bin/phpcs --standard=PSR2 src/
  - ./vendor/bin/phpunit --coverage-text -c test/phpunit.xml
