---
language: php
php:
  - '5.6'
  - '7.0'
  - 'nightly'

install:
  - composer install

before_script:
  - pecl install yaml

script:
  - ./vendor/bin/phpcs --standard=PSR2 src/
  - ./vendor/bin/phpunit --coverage-text -c test/phpunit.xml
